##
server:
  port: 8181
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.22.226:1521:XE
    username: ZHKS-TEST
    password: ZHKS-TEST
    driver-class-name: oracle.jdbc.OracleDriver
  application:
    name: zhks-web
eureka:
  client:
    service-url:
      defaultZone: http://192.168.22.163:7001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
FTP_ADDRESS: 192.168.22.225
FTP_PORT: 21
FTP_USERNAME: 1
FTP_PASSWORD: 1
WordBriefBasePath: tomcat/webapps/zhks/